// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJT14PnK-IxiJkOYrMshYCPSMqKNatwPo',
    appId: '1:262301485745:web:7a3ceda0f8d80dceaaf090',
    messagingSenderId: '262301485745',
    projectId: 'application-name-91fa1',
    authDomain: 'application-name-91fa1.firebaseapp.com',
    storageBucket: 'application-name-91fa1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqV4VFW3WLnojK8ANlgksRiehfJgOssEY',
    appId: '1:262301485745:android:51ced5d76fd4bf77aaf090',
    messagingSenderId: '262301485745',
    projectId: 'application-name-91fa1',
    storageBucket: 'application-name-91fa1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1G2_cbLbnr0eodA-rcDUVTVhX_-Fh2yk',
    appId: '1:262301485745:ios:2ecd2d56f20f219baaf090',
    messagingSenderId: '262301485745',
    projectId: 'application-name-91fa1',
    storageBucket: 'application-name-91fa1.appspot.com',
    iosClientId: '262301485745-orlppmlh3k27ak3ahn98iulfoled3b8c.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1G2_cbLbnr0eodA-rcDUVTVhX_-Fh2yk',
    appId: '1:262301485745:ios:2ecd2d56f20f219baaf090',
    messagingSenderId: '262301485745',
    projectId: 'application-name-91fa1',
    storageBucket: 'application-name-91fa1.appspot.com',
    iosClientId: '262301485745-orlppmlh3k27ak3ahn98iulfoled3b8c.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoapp',
  );
}
